### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HarrisRobin** [sippingElixir/phoenix-hangouts#1]
# Phoenix Hangouts - Roadmap  
This epic describes the current status and upcoming milestones of Phoenix Hangouts.
_updated Monday, 26 December 2016_

## General
- [ ] Setup project boilerplate.
- [ ] Spec out features and milestones.

## Database 
- [ ] Implement database design and models.

## Design 
- [ ] Make logo for sippingElixir.
- [ ] Design hangouts clone.

**Comment by christiansakai** [comment]
@HarrisRobin @Arieg419 

Some thoughts on spec:

1. Can you change the repo to just `hangouts`? Its just so that it is easier to write `Hangouts` rather than `PhoenixHangouts` everytime lol. We can change it later if you want

2. What do you think of hybrid approach rather than full separation of client/server. So basically only some pages are React based. Other pages are rendered by Phoenix. Because:
    * We want to learn Elixir/Phoenix and not React/Redux/JS
    * Server side rendering FTW, so we don't need to worry about SEO
    * We'll decide which pages require React. For example, maybe logged in pages will use React? Non logged in pages just use Phoenix.
 
3. Are we using Webpack or Brunch? If you want, you can configure the Webpack, Harris?

**Comment by HarrisRobin** [comment]
@christiansakai completely agree on not making everything in reactJS.

1. Done.
2. Agreed. I'm even open to not using reactJS at all, we'll to discuss.
3. Let's go with webpack imo. I can take care of that.

**Comment by christiansakai** [comment]
@HarrisRobin cool. Lets spec up a crude spec on the app

**Comment by christiansakai** [comment]
@HarrisRobin @Arieg419 Another thing to do which is a good practice and also help us learn about OTP. Is to make microservices separate. So, for example, we have some logic in our app that does something that can be isolated, we can make a separate repo for that, and make that as a dependency. In this way, we can learn separately how to build small Elixir (not Phoenix) projects, with its own documentation and testing.

**Comment by HarrisRobin** [comment]
@christiansakai cool,
1. So if I understand correctly, the microservices are basically small elixir modules that are spawned as processes in the main application(master) ?

2. These dependencies are included using mix?
